### ISSUE TITLE
xmpp-im/s5b.cpp:2117: bad if test ?

### ISSUE THREAD

**Issue by dcb314** [psi-im/iris#12]
Source code is

void S5BServer::ss_incomingUDP(const QString &host, int port, const QHostAddress &addr, int sourcePort, const QByteArray &data)
{
    if(port != 0 || port != 1)
        return;

Suggest swap || for &&. This bug found by gcc compiler flag -Wlogical-op.

**Comment by Ri0n** [comment]
I checked again the code. It does not look valid at all but I'll apply suggested fix just to make compiler happy.
