### ISSUE TITLE
Cannot send messages with codepoints outside of BOM

### ISSUE THREAD

**Issue by njaard** [psi-im/iris#13]
When using Kopete, when I send a message with a codepoint out of the unicode BOM, I get disconnected from the XMPP server. BOM characters include things like Emoji characters, and more generally, things that representable by UCS-2.

See my original bug: https://bugs.kde.org/show_bug.cgi?id=314272

Receiving such characters works fine.

If I send U1F431, Kopete appears to say in its log:

kopete(17681)/kopete (jabber - raw protocol) JabberAccount::slotClientDebugMessage: "XML OUT: <message type="chat" to="[[Sensored IM address]]" id="19"> <body>&#xdc31;</body> <x xmlns="jabber:x:event"> <offline/> <composing/> <delivered/> <displayed/> </x> <active xmlns="http://jabber.org/protocol/chatstates"/> <request xmlns="urn:xmpp:receipts"/> </message> "

Dropping invalid XML char U+d83d.

**Comment by wadealer** [comment]
njaard, is this still actual?

**Comment by pali** [comment]
Ops, I found that this problem is already reported. More info in https://github.com/psi-im/iris/issues/42

**Comment by pali** [comment]
Should be fixed by https://github.com/psi-im/iris/pull/44
