### ISSUE TITLE
facebook-jabber is broken, but it's possible to get it back working

### ISSUE THREAD

**Issue by ascomycota** [psi-im/iris#29]
I know that facebook cancelled jabber. But my android app "Xabber" still can communicate. Seems like the protocol from facebook changed sligthly and Xabber is more tolerant.

Any ideas to get that fixed?

I use kopete and want to chat with my facebook friends again ;-)

**Comment by Ri0n** [comment]
Try to build from gjt

**Comment by ascomycota** [comment]
Is it resolved? :)

**Comment by Ri0n** [comment]
yep. but faceook-xmpp is not really xmpp. So don't expect flawless work.
