### ISSUE TITLE
Stall while "Connecting" in Psi-plus and Kopete with jabberd2

### ISSUE THREAD

**Issue by stbuehler** [psi-im/iris#4]
Hi,

jabberd2 only sends one "challenge" for sasl auth (it seems other servers send a second challenge which is answered with an empty response by psi-plus/kopete).
Neither psi-plus nor kopete finish the connect after they get the success event from the server, both claim in the xml console they sent more data, but this never hits the network (checked with wireshark more than once).
(ekg2 works as it actually sends the data.)

<pre>
[...]

server -&gt; client
	&lt;stream:features&gt;
	&lt;mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"&gt;
	&lt;mechanism&gt;PLAIN&lt;/mechanism&gt;
	&lt;mechanism&gt;DIGEST-MD5&lt;/mechanism&gt;
	&lt;/mechanisms&gt;
	&lt;auth xmlns="http://jabber.org/features/iq-auth"/&gt;
	&lt;register xmlns="http://jabber.org/features/iq-register"/&gt;
	&lt;/stream:features&gt;

client -&gt; server
	&lt;auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="DIGEST-MD5"/&gt;

server -&gt; client
	&lt;challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl"&gt;[...]&lt;/challenge&gt;

client -&gt; server
	&lt;response xmlns="urn:ietf:params:xml:ns:xmpp-sasl"&gt;[...]&lt;/response&gt;

server -&gt; client
	&lt;success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/&gt;

client -&gt; server (only shown in console, never reaches the network)
	&lt;?xml version="1.0"?&gt;

	&lt;stream:stream xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xmlns="jabber:client" to="[...]"&gt;
</pre>

**Comment by wadealer** [comment]
Is this still actual?

**Comment by Ri0n** [comment]
According to Jebberd2 mail list that was a problem with some encryption library which is most likely fixed already since I see other reports with working Psi.
