### ISSUE TITLE
Frequent disconnects in Kopete on fast networks

### ISSUE THREAD

**Issue by hydroo** [psi-im/iris#41]
Hi iris-developers,

Kopete (which uses iris for jabber), frequently disconnects on university LAN and is therefore unusable.
The issue seems to be only if the connection is very fast.
WLAN or DSL is fine.

My current workaround is https://bugs.launchpad.net/ubuntu/+source/kdenetwork/+bug/486518/comments/10 .

The following bugs (or some of them) are probably related:

https://bugs.kde.org/show_bug.cgi?id=365092
https://bugs.kde.org/show_bug.cgi?id=198789
https://bugs.launchpad.net/ubuntu/+source/kdenetwork/+bug/486518

Thanks for your help and best regards,
Ronny

I use: Kubuntu 16.04, kopete Qt: 4.8.7, KDE Development Platform: 4.14.16, Kopete: 1.8.3.
I don't know what iris' version is. How do I find out?

**Comment by Ri0n** [comment]
Hi

could you provide some logs? xml log for example. Also try other applications with iris library (Psi/Psi+ for example). 
I'd like to know exact iris revision failing for you.

**Comment by hydroo** [comment]
Hi,
sorry for the delay.

I just tried to reproduce the issue but couldn't.
With psi and psi-plus it worked, too.
(I don't use kopete mainly anymore, because OTR is broken)

I will attempt a few more the next days/weeks and maybe reopen the issue and provide logs.

Thanks and best regards,
Ronny
