### ISSUE TITLE
jdns in linux don't work if /etc/resolv.conf havе ipv6 nameservers only

### ISSUE THREAD

**Issue by shanechko** [psi-im/iris#7]
psi unable to connect in pure ipv6 network (not dual stack ipv4+ipv6).

jdns unable to get ipv6 nameservers from /etc/resolv.conf

Bug possible in https://github.com/psi-im/iris/blob/master/src/jdns/jdns_sys.c#L756
using nscount instead of nscount6.

With my config (one ipv6 nameserver in resolv.conf) res_ninit (glibc 2.15) returns:
res._ext.nscount = 0
res._ext.nscount6 = 1
res.nscount = 1

**Comment by Ri0n** [comment]
btw is it working now as expected?

**Comment by Neustradamus** [comment]
@shanechko: It works now?

**Comment by shanechko** [comment]
@Neustradamus I'm not able to verify issue after 11 years. 
I don't have active xmpp account and native ipv6 connection. 

BTW I will try to check.

**Comment by shanechko** [comment]
@Neustradamus @Ri0n it is works as expected, thanks!!

Psi v1.5.1973 (2024-06-15, e336abc3)
